sudo: false
language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc

metrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: beta-xcode6.1

addons:
   apt:
      sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
      packages: ['clang-3.6' , 'zlib1g-dev', 'libbz2-dev', 'libsnappy-dev', 'curl']
env:
  # DeleteObsoleteFilesPendingOutputs
  - JOB_NAME=shake_flaky

install:
  # Build gflags
  # TODO(noetzli): Remove when gflags available through Travis
  - pushd /tmp/ && curl -L https://github.com/gflags/gflags/archive/v2.1.2.tar.gz -o gflags.tar.gz && tar xfz gflags.tar.gz && cd gflags-2.1.2 && cmake . && make && popd

before_script:
  # Add gflags to include/library paths
  # TODO(noetzli): Remove when gflags available through Travis
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/tmp/gflags-2.1.2/lib"
  - export LIBRARY_PATH="$LIBRARY_PATH:/tmp/gflags-2.1.2/lib"
  - export CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:/tmp/gflags-2.1.2/include"
  - if [[ "${TRAVIS_OS_NAME}" == 'linux' ]]; then CXX=clang++-3.6; fi
  - if [[ "${TRAVIS_OS_NAME}" == 'osx' ]]; then brew install gflags snappy; fi
  # Limit the maximum number of open file descriptors to 2000
  - ulimit -n 2000 || true

script:
  - OPT=-DTRAVIS V=1 make -j4 db_sst_test; ./db_sst_test --gtest_filter=*DeleteObsoleteFilesPendingOutputs
notifications:
    email:
      - leveldb@fb.com
    webhooks:
      - https://buildtimetrend.herokuapp.com/travis
